---
- name: Install PostgreSQL
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: "Configure access control"
  template:
    src: "pg_hba.conf"
    dest: "/etc/postgresql/9.5/main/pg_hba.conf"

- name: Ensure Super User Account
  become: yes
  become_user: postgres
  postgresql_user: name={{ ansible_user|default(lookup('env', 'USER'), True) }}
                   state=present
                   role_attr_flags=LOGIN,SUPERUSER

- name: Create database for Super User account
  become: yes
  become_user: postgres
  postgresql_db: name={{ ansible_user|default(lookup('env', 'USER'), True) }}
                 state=present
                 owner={{ ansible_user|default(lookup('env', 'USER'), True) }}
...
