---
- name: "Load os-specific variables"
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"

- name: "Install PostgreSQL"
  apt:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
      - 'acl'
      - "postgresql"
      - "libpq-dev"
      - 'postgis'
      - 'python3-psycopg2'

- name: "Configure network listener"
  lineinfile:
    path: "{{ postgresql_config_path }}/postgresql.conf"
    regexp: "listen_addresses"
    line: "listen_addresses = '*'     # what IP address(es) to listen on;"
  notify: "postgresql_restart"

- name: "Configure the firewall (postgres)"
  ufw:
    rule: "allow"
    port: "postgres"

- name: "Create backup directory"
  file:
    path: "/srv/backups/postgres"
    state: "directory"
    group: "staff"
    mode:  "u=rwX,g=rwXs,o=rX"

- name: "Install cron backup script"
  template:
    src: "backup.sh"
    dest: "/etc/cron.daily/backup.d/postgres"
    mode: "0755"
...
